name: zen_flutter
description: Flutter template for Zencode mobile projects
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  intl: ^0.18.0
  go_router: ^13.1.0
  flutter_screenutil: ^5.9.0
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  freezed_annotation: ^2.4.1
  flutter_dotenv: ^5.1.0
  fpdart: ^1.1.0
  get_it: ^7.6.7
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  sentry_flutter: ^7.16.0
  sentry_logging: ^7.16.0
  logging: ^1.2.0
  dartx: ^1.2.0
  json_annotation: ^4.8.1
  bloc_concurrency: ^0.2.3
  rxdart: ^0.27.7
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^5.13.0
  build_runner: ^2.4.8
  bloc_test: ^9.1.4
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.6
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/
